// src/lib/components/Editor.svelte
<script lang="ts">
  import { initializeEditor } from "./LigatureEditor.ts"
  import { browser } from '$app/environment'
  import { state } from "$lib/stores.js";
  import { getContext } from "svelte";
	import { printNetwork } from "@ligature/ligature";

  if (browser) {
    let engine = getContext("engine")
    setTimeout(() => {
      initializeEditor({
        engine: engine,
        element: document.querySelector("#editor"),
        onRun: (text: string) => {
          state.set(engine.run(text))
        },
        onChange: (text: string) => {}
      })
    })
  }
</script>

<div id="editor"></div>

// ligature-lab/src/components/Editor.tsx
import {initializeEditor} from '@ligature/ligature-components/src/editor/ligature-editor'
import { runScript } from './Repl';

export function Editor(props) {
    console.log(props)
    setTimeout(() => {
        initializeEditor({
            element: document.querySelector("#editor"),
            onRun: async (script) => {
                const result = await runScript(script) 
                props.setResult("testtttt") },
            onChange: () => {}
        })
    })
    return <div id="editor"></div>;
}
