// ligature-lab/src/components/Graphs.svelte
<script lang="ts">
import AddGraph from "./AddGraph.svelte";
</script>

<div id="graphs" class="content">
    <h2 class="title is-3 is-inline">Graphs</h2>
    <AddGraph />
    <!-- <button id="addGraph" class="button" on:click={addGraph}>Add Graph</button> -->

    <ul>
        <li><a href="/graphs/sample">Sample Graph</a></li>
    </ul>
</div>

// ligature-lab/src/components/Graphs.tsx
import { For } from 'solid-js';
import {AddGraph} from './AddGraph';

export function Graphs(props) {
  return <div id="graphs">
    <AddGraph></AddGraph>
    <h2>Graphs</h2>
    <ul>
      <For each={props.datasets}>
        { (graph) =>
          <li>
            <a href={`/graph/${graph}`}>
              {graph}
            </a>
          </li>
        }
      </For>
    </ul>
  </div>;
}
