// src/lib/LigatureInstance.svelte
<script>
    import { Modal } from 'bootstrap';
	import { createEventDispatcher, onMount } from 'svelte'
	const dispatch = createEventDispatcher()

    export let datasets = []

    let datasetToRemove = ""
    let datasetToAdd = ""

    onMount(async () => {
        document.getElementById('addDatasetModal').addEventListener('show.bs.modal', function () {
            datasetToAdd = ""
        })

        document.getElementById('addDatasetModal').addEventListener('shown.bs.modal', function () {
            document.getElementById('datasetName').focus()  
        })
    })

    function addDataset(name) {
        dispatch('addDataset', {name})
    }

    function removeDataset(name) {
        dispatch('removeDataset', {name})
    }

    function refreshDatasets() {
        dispatch('refreshDatasets')
    }
</script>
  
<div class="container">
    <div class="row">
        <div class="col">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addDatasetModal">
                Add Dataset
            </button>            
        </div>  
        <div class="col">
            <button on:click={refreshDatasets} type="button" class="btn btn-primary float-end">Refresh</button>
        </div>
    </div>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Dataset Name</th>
                    <th scope="col">Remove?</th>
                </tr>
            </thead>
            <tbody>
                {#each datasets as dataset}
                    <tr>
                        <td>
                            {dataset}
                        </td>
                        <td>
                            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#removeDatasetModal" on:click={e => datasetToRemove = dataset}>Remove</button>
                        </td>
                    </tr>
                {/each}
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="addDatasetModal" tabindex="-1" aria-labelledby="addDatasetModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addDatasetModalLabel">Add Dataset</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="field">
                    <label for="datasetName" class="label">Name</label>
                    <div class="control">
                        <input id="datasetName" class="input" type="text" bind:value={datasetToAdd}>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" on:click={e => addDataset(datasetToAdd)}>Add Dataset</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="removeDatasetModal" tabindex="-1" aria-labelledby="removeDatasetModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeDatasetModalLabel">Remove Dataset</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Remove {datasetToRemove}?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" on:click={e => removeDataset(datasetToRemove)}>Remove</button>
            </div>
        </div>
    </div>
</div>  

<style>
    @import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';
</style>

// src/LigatureInstance.tsx
import AddDatasetModal from './AddDatasetModal'
import { createEffect, createSignal, onMount } from 'solid-js'
import RemoveDatasetModal from './RemoveDatasetModal'

type LigatureInstanceCompanion = {
  datasets: () => string[]
  addDataset: (dataset: string) => Promise<void>
  removeDataset: (dataset: string) => Promise<void>
  selectDataset: (dataset: string) => Promise<void>
  refreshDatasets: () => Promise<void>
}

function LigatureInstance(props: LigatureInstanceCompanion) {
  const [showAddDatasetModal, setShowAddDatasetModal] = createSignal(false)
  const [showRemoveDatasetModal, setShowRemoveDatasetModal] = createSignal(false)
  const [datasetToRemove, setDatasetToRemove] = createSignal(null)
  onMount(async () => {
    const addDatasetButton = document.querySelector('#addDatasetButton')
    const refreshDatasetsButton = document.querySelector('#refreshDatasetsButton')
    addDatasetButton.addEventListener('click', () => setShowAddDatasetModal(true))
    refreshDatasetsButton.addEventListener('click', async () => props.refreshDatasets())
  })

  function addDataset(dataset: string) {
    props.addDataset(dataset)
  }

  return <>
    <div bp="container">
        <sl-button id="addDatasetButton" bp="float-left" variant="primary" outline>Add Dataset</sl-button>
        <sl-button id="refreshDatasetsButton" bp="float-right" variant="primary" outline>Refresh</sl-button>
        <div bp="clear-fix"></div>
    </div>
    <div bp="container">
      <table>
        <thead>
          <tr>
            <th>Dataset Name</th>
            <th>Remove?</th>
          </tr>
        </thead>
        <tbody>
          <For each={props.datasets()}>{(dataset) =>
            <DatasetRow dataset={dataset} datasetToRemove={setDatasetToRemove} selectDataset={props.selectDataset}></DatasetRow>
          }</For>
        </tbody>
      </table>
    </div>

    <AddDatasetModal addDataset={props.addDataset} show={showAddDatasetModal} setShow={setShowAddDatasetModal}></AddDatasetModal>
    <RemoveDatasetModal removeDataset={props.removeDataset} dataset={datasetToRemove} show={showRemoveDatasetModal} setShow={setShowRemoveDatasetModal}></RemoveDatasetModal>
  </>
}

type DatasetRowCompanion = {
  dataset: string
  removeDataset: (dataset: string) => Promise<void>
  datasetToRemove: (dataset: string) => string
  selectDataset: (dataset: string) => Promise<void>
}

function DatasetRow(props: DatasetRowCompanion) {
  onMount(async () => {
    const dialog = document.querySelector('#removeDatasetDialog')
    const removeDatasetButton = document.querySelector("#removeDataset" + props.dataset)
    props.datasetToRemove(props.dataset)
    removeDatasetButton.addEventListener('click', () => {
      props.datasetToRemove(props.dataset)
      dialog.show()
    })
  })

  return <tr>
    <td><sl-button variant="text" onClick={() => props.selectDataset(props.dataset)}>{props.dataset}</sl-button></td>
    <td><sl-button variant="danger" outline id={"removeDataset" + props.dataset}>Remove</sl-button></td>
  </tr>
}

export default LigatureInstance
