// ligature-lab/src/components/Editor.tsx
import { onMount } from "solid-js";
import { EditorView, basicSetup } from "codemirror";
import { keymap } from "@codemirror/view"
import { indentWithTab } from "@codemirror/commands"

export function Editor(props: any) {
  onMount(async () => {
      initializeEditor("editor", props.text, props.run);
  })
  return <div id="editor" class="code"></div>
}

export function initializeEditor(id: string, setText, run) {
  let inputEditor: EditorView;
  let runEvent;

  const editorNode = document.getElementById(id)!!;
  inputEditor = new EditorView({
    extensions: [
      EditorView.theme({
        "&": {height: "300px", overflow: "auto", resize: "vertical"},
        ".cm-scroller": {overflow: "auto"}
      }),
      EditorView.domEventHandlers({
        keydown: e => {
          if((e.code == "Enter") && (e.metaKey || e.ctrlKey)) {
            e.preventDefault();
          }
        }
      }),
      EditorView.updateListener.of((v: ViewUpdate) => {
        if (v.docChanged) {
          setText(v.state.doc.toString())
        }
      }),
      basicSetup,
      keymap.of([indentWithTab]), 
      ],
      parent: editorNode,
    });
    inputEditor.focus();
    runEvent = (e) => {
      if((e.code == "Enter") && (e.metaKey || e.ctrlKey)) {
          run(inputEditor.state.doc.toString());
      }
    };
    runEvent = document.body.addEventListener('keydown', runEvent);
}

// ligature-components/src/lib/Editor.svelte
<script lang="ts">
    import "bulma/css/bulma.css";
    import { onMount, createEventDispatcher } from 'svelte';
    import {EditorView, basicSetup} from "codemirror";
    import {EditorState} from "@codemirror/state";
    import {javascript} from "@codemirror/lang-javascript";
    let inputEditor: EditorView | null = null;
    const dispatch = createEventDispatcher();
    onMount(async () => {
        document.body.addEventListener('keydown', function(e) {
            if((e.code == "Enter") && (e.metaKey || e.ctrlKey)) {
                runQuery();
            }
        });
        const editorNode = document.getElementById("textEditor")!!;
        inputEditor = new EditorView({
            extensions: [
                EditorView.domEventHandlers({
                    keydown: e => {
                        if((e.code == "Enter") && (e.metaKey || e.ctrlKey)) {
                            e.preventDefault();
                        }
                    }
                }),
                basicSetup, 
                javascript()
            ],
            parent: editorNode
        });
        inputEditor.focus();
    });
    async function runQuery() {
        dispatch('runQuery', inputEditor!!.state.doc.toString());
    }
    function clear() {
        inputEditor!!.setState(EditorState.create({
            doc: "", 
            extensions: [
                EditorView.domEventHandlers({
                    keydown: e => {
                        if((e.code == "Enter") && (e.metaKey || e.ctrlKey)) {
                            e.preventDefault();
                        }
                    }
                }),
                basicSetup, 
                javascript()
            ]
        }))
        dispatch('clear');
    }
</script>

<div id="query">
    <button class="button" on:click={() => runQuery()}>Run</button>
    <button class="button" on:click={() => clear()}>Clear</button>
</div>

<div id="textEditor"></div>

<style>
    #textEditor {
        height:300px;
        resize: vertical;
        overflow:scroll;
    }
</style>
